name: MPI
channels:
  - bioconda
  - conda-forge
dependencies:
  - htslib
  - mash
  - python=3.10
  - samtools
  - snakemake
  - pggb
  - multiqc
  - numpy
  - pandas
  - gfapy
  - plotly
  - python-kaleido
  - igraph 
